class RepositoryException(Exception): ...


class AccessDenied(Exception): ...


class ResultNotFound(RepositoryException): ...


class AuthorizationException(Exception): ...


class WrongCredentials(RepositoryException): ...


class ForeignKeyError(RepositoryException): ...


class JwtException(AuthorizationException): ...


class JwtExpired(JwtException): ...


class JwtInvalid(JwtException): ...


class RefreshException(AuthorizationException): ...


class RefreshExpired(RefreshException): ...


class RefreshInvalid(RefreshException): ...


class VerificationException(Exception): ...


class RefreshClientInfoIncorrect(RefreshException): ...


class FileNotFound(Exception): ...


class UserNotRegistered(Exception): ...


class PlaceOrderForeignKeyError(Exception): ...


class UserAlreadyExist(Exception): ...
